version: "3.8"

services: 
    db:
        image: mysql:latest
        container_name: deno-blog-db-dev
        command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
        restart: always
        volumes: 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: password
    api:
        build: ./api
        image: deno-blog-api:dev
        container_name: deno-blog-api-dev
        restart: always
        depends_on: 
            - db
        volumes: 
            - ./api:/usr/app
        ports: 
            - 3000:3000
        environment: 
            - DB_HOST=db # this should be identical to the database service name
            - DB_USER=root
            - DB_DATABASE=blog
            - DB_PASSWORD=password
            - TOKEN_SECRET=secret

volumes:
    db-data:
        name: deno-blog-db-dev-data